tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
brew 'autoconf'
brew 'dnsmasq', restart_service: true
brew 'git'
brew 'hub'
brew 'libyaml'
brew 'openssl'
brew 'mongodb', restart_service: true
brew 'n'
brew 'node'
brew 'pkg-config'
brew 'sqlite'
brew 'vcprompt'
